### ISSUE TITLE
java integration

### ISSUE THREAD

**Issue by elientumba2019** [levibostian/Shutter-Android#6]
can this library be used with java code ?

**Comment by levibostian** [comment]
Yes, it *should* be 100% compatible with Java code. However, I have not tested it. 

In the code samples, I show code such as: `Shutter.with(this)` which *may* need to be called like this instead: `Shutter.Companion.with(this)`. 

It could be made *better* to work with Java, but yes, it should work just fine. Pull requests are welcome if you wish to improve it. I may get to it at some point as well.

**Comment by levibostian** [comment]
You can subscribe to [this issue](https://github.com/levibostian/Shutter-Android/issues/7) for progress on making this library **more** compatible with Java (then it already is).
